dist: xenial

language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"

matrix:
    allow_failures:
        - python: "nightly"

install:
    - pip install -r requirements-testing.txt

script:
    - bash scripts/test.sh

after_script:
    - bash <(curl -s https://codecov.io/bash)

deploy:
    provider: script
    script: bash scripts/deploy.sh
    on:
        tags: true
        python: "3.6"
